modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "combat_rebalance"
version = "${version}"
displayName = "Combat Rebalanced"
authors = "Me!"
description = "A Mod Tweaking and Rebalancing Minecraft's Combat!"
#logoFile = ""

[[dependencies.combat_rebalance]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.combat_rebalance]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.combat_rebalance]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.combat_rebalance]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.1+1.21-neoforge,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "combat_rebalance.mixins.json"
